### ISSUE TITLE
How to remove authentication/log in feature from the template?

### ISSUE THREAD

**Issue by koolkunz** [ng-matero/ng-matero#455]
Hi, I am trying to remove the authentication feature in the template but I am struggling to get the project to work after removing the auth files. Please guide me how to proceed.

Note: I am building a website which doesn't require login/logout facility, it's a static company profile website

**Comment by nzbin** [comment]
1. Remove the `AuthGuard`
https://github.com/ng-matero/ng-matero/blob/1f25809ef0067d52abcdb78fab9270298ba5c3a6/src/app/routes/routes-routing.module.ts#L19-L20

2. Refactor the load logic since the `AuthService` is useless
https://github.com/ng-matero/ng-matero/blob/1f25809ef0067d52abcdb78fab9270298ba5c3a6/src/app/core/bootstrap/startup.service.ts#L22-L36

**Comment by koolkunz** [comment]
Thanks for the quick reply!
As per your suggestion, I was able to get it done by making these changes in startup.service.ts:
`load() {
    return new Promise<void>(resolve => {
      this.menu()
        .pipe(tap(menu => this.setMenu(menu)))
        .subscribe(
          () => resolve(),
          () => resolve()
        );
    });
  }

  menu() {
    return this.http
      .get<{ menu: Menu[] }>('assets/data/menu.json?_t=' + Date.now())
      .pipe(map(res => res.menu));
  }`
